version: "3.7"

networks:
  main:
    driver: bridge

services:
  nsqlookupd:
    build:
      context: ./nsqlookupd/
    networks:
      - main
  nsqd:
    build:
      context: ./nsqd/
    depends_on:
      - nsqlookupd
    networks:
      - main
  dnsd:
    build:
      context: ./dnsd/
    depends_on:
      - nsqd
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
    networks:
      - main
  http:
    build:
      context: ./http/
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - ws
    networks:
      - main
  ws:
    build:
      context: ./ws/
    depends_on:
      - nsqd
    networks:
      - main
