version: "3.7"

services:
  nsqlookupd:
    build:
      context: ./nsqlookupd/
  nsqd:
    build:
      context: ./nsqd/
    depends_on:
      - nsqlookupd
  http:
    build:
      context: ./http/
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
