version: "3.7"

services:
  nsqlookupd:
    build:
      context: ./nsqlookupd/
  nsqd:
    build:
      context: ./nsqd/
    depends_on:
      - nsqlookupd
  dnsd:
    build:
      context: ./dnsd/
    depends_on:
      - nsqd
    ports:
      - target: 53
        published: 1053
        protocol: udp
        mode: host
  http:
    build:
      context: ./http/
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
  ws:
    build:
      context: ./ws/
    depends_on:
      - nsqd
      - http
